{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mongodb_service_status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_service_status", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "opccounters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_opcounters_.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "opccounters",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_opcounters_.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "opcountersRepl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_opcountersRepl.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "opcountersRepl",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_opcountersRepl.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_mem.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 32 },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_connections.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "connection",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_connections.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_network.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_network.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_global_lock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_globalLock.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_global_lock",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^mongodb_globalLock.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_indexCounters.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_indexCounters.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_dbStats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_dbStats.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodbdbStats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_dbStats.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_cpu.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_cpu",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_cpu.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_asserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_asserts.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_asserts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_asserts.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_opLatencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_opLatencies.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mongodb_opLatencies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_opLatencies.*\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}