version: "3.8"

services:
  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana_prometheus
    restart: no
    ports:
      - '3000:3000'
    volumes:
      - D:/Operations/monitor/grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini  # Mount the grafana.ini file
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.53.2
    container_name: prometheus
    volumes:
      - D:/Operations/monitor/prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

volumes:
  grafana_data: {}

networks:
  monitoring:
    driver: bridge
