global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'host.docker.internal:8001' ]